
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    expose:
      - 3306
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    expose:
      - 9000
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
      
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /Users/kawaharadaryou/Documents/c/rkawahar/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /Users/kawaharadaryou/Documents/c/rkawahar/data/html
      o: bind

networks:
  inception:
    name: inception
    driver: bridge
